require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'HICenter' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'HICenterTests' do
    inherit! :complete
    # Pods for testing
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # add pods for desired Firebase products
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
#
target 'HICenterEx' do
  pod 'Firebase/Messaging', '~> 8.6.0' # eg 6.31.0
end
